/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlnhahangtieccuoi;

import Process.HopDong;
import Process.NhanVien;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

/**
 *
 * @author Thang Le
 */
public class LapHopDong extends javax.swing.JFrame {

     NhanVien nv = new NhanVien();
     HopDong hd = new HopDong();
    /**
     * Creates new form LapHopDong
     */
    public LapHopDong() {
        initComponents();
        ImageIcon img = new ImageIcon("E:\\java\\QLNhaHang\\QLNhaHangTiecCuoi\\src\\Database/2.jpg");
        this.setIconImage(img.getImage());
        ShowDataCmbNV();
        ShowDataCmbTD();
        ShowDataCmbDV();
        ShowDataKH();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbMaNV = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtTenChuRe = new javax.swing.JTextField();
        txtTenCoDau = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtTenKhachHang = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtTienCoc = new javax.swing.JTextField();
        cmbSoLuongBan = new javax.swing.JComboBox();
        cmbSoLuongNV = new javax.swing.JComboBox();
        txtNgayToChuc = new com.toedter.calendar.JDateChooser();
        txtNgayLap = new com.toedter.calendar.JDateChooser();
        jPanel9 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        cmbThucDon = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        txtMonKhaiVi = new javax.swing.JTextField();
        txtMonChinh1 = new javax.swing.JTextField();
        txtMonChinh2 = new javax.swing.JTextField();
        txtMonChinh3 = new javax.swing.JTextField();
        txtLau = new javax.swing.JTextField();
        txtTrangMieng = new javax.swing.JTextField();
        txtBia = new javax.swing.JTextField();
        txtNuocNgot = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cmbDichVu = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        txtRuou = new javax.swing.JTextField();
        txtBanhKem = new javax.swing.JTextField();
        txtMC = new javax.swing.JTextField();
        txtBanNhac = new javax.swing.JTextField();
        txtCaSi = new javax.swing.JTextField();
        txtDJ = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTienTrangTri = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtThue = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtGiaThucDon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtGiaDichVu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSoTienThieu = new javax.swing.JTextField();
        txtTongTien = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnTinh = new javax.swing.JButton();
        btnLapHopDong = new javax.swing.JButton();
        btnXemHopDong = new javax.swing.JButton();
        btnQuayVe = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        txtMaHD1 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Lập hợp đồng đặt tiêc");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 0, 272, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã Hợp Đồng:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        getContentPane().add(txtMaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 54, 60, 32));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mã Nhân Viên:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 56, -1, 20));

        cmbMaNV.setToolTipText("");
        cmbMaNV.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMaNVItemStateChanged(evt);
            }
        });
        cmbMaNV.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                cmbMaNVAncestorRemoved(evt);
            }
        });
        cmbMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMaNVActionPerformed(evt);
            }
        });
        getContentPane().add(cmbMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 52, 104, 32));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tên NV:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 55, -1, 22));

        txtTenNV.setEditable(false);
        txtTenNV.setEnabled(false);
        getContentPane().add(txtTenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 52, 138, 32));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin khách hàng"));

        jLabel11.setText("Ngày Lập:");

        jLabel12.setText("Tên Khách Hàng:");

        jLabel13.setText("Tên Chú Rể:");

        jLabel14.setText("Tên Cô Dâu");

        jLabel15.setText("Địa Chỉ:");

        jLabel16.setText("Số Điện Thoại:");

        jLabel17.setText("Số Lượng Bàn:");

        jLabel18.setText("Số lượng NV:");

        jLabel19.setText("Ngày Tổ Chức:");

        jLabel20.setText("Tiền Cọc:");

        txtTienCoc.setText("0");

        cmbSoLuongBan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "40", "60", "80", "100" }));

        cmbSoLuongNV.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "20", "30", "40" }));

        txtNgayToChuc.setDateFormatString("yyyy-MM-dd");

        txtNgayLap.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTienCoc, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(txtNgayToChuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel11)
                            .addComponent(jLabel16)
                            .addComponent(jLabel12)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbSoLuongBan, 0, 209, Short.MAX_VALUE)
                            .addComponent(cmbSoLuongNV, 0, 209, Short.MAX_VALUE)
                            .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(txtTenCoDau, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(txtTenChuRe, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(txtTenKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(txtNgayLap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(35, 35, 35))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenChuRe, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenCoDau, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(cmbSoLuongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cmbSoLuongNV, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(txtNgayToChuc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtTienCoc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 100, -1, -1));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin đặt tiệc"));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Thực đơn"));

        cmbThucDon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbThucDonItemStateChanged(evt);
            }
        });

        jLabel21.setText("Mã Thực Đơn:");

        txtMonKhaiVi.setEnabled(false);

        txtMonChinh1.setEnabled(false);

        txtMonChinh2.setEnabled(false);

        txtMonChinh3.setEnabled(false);

        txtLau.setEnabled(false);

        txtTrangMieng.setEnabled(false);

        txtBia.setEnabled(false);

        txtNuocNgot.setEnabled(false);

        jLabel22.setText("Món khai vị:");

        jLabel23.setText("Món chính 1:");

        jLabel24.setText("Món Chính 2:");

        jLabel25.setText("Món Chính 3:");

        jLabel26.setText("Lẩu:");

        jLabel27.setText("Tráng miệng:");

        jLabel28.setText("Bia:");

        jLabel29.setText("Nước ngọt:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addGap(39, 39, 39)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMonChinh1)
                    .addComponent(cmbThucDon, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonKhaiVi)
                    .addComponent(txtMonChinh2, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(txtMonChinh3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addGap(58, 58, 58)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTrangMieng)
                    .addComponent(txtLau, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(txtBia)
                    .addComponent(txtNuocNgot))
                .addGap(21, 21, 21))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbThucDon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMonKhaiVi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLau, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMonChinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTrangMieng, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMonChinh2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMonChinh3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNuocNgot, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel29))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dịch vụ"));

        cmbDichVu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDichVuItemStateChanged(evt);
            }
        });

        jLabel30.setText("Mã dịch vụ:");

        txtRuou.setEditable(false);
        txtRuou.setEnabled(false);

        txtBanhKem.setEditable(false);
        txtBanhKem.setEnabled(false);

        txtMC.setEditable(false);
        txtMC.setEnabled(false);

        txtBanNhac.setEditable(false);
        txtBanNhac.setEnabled(false);

        txtCaSi.setEditable(false);
        txtCaSi.setEnabled(false);

        txtDJ.setEditable(false);
        txtDJ.setEnabled(false);

        jLabel31.setText("Rượu:");

        jLabel32.setText("Bánh Kem:");

        jLabel33.setText("MC:");

        jLabel34.setText("Ban Nhạc:");

        jLabel35.setText("Ca sĩ:");

        jLabel36.setText("DJ:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtRuou, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel34))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtMC, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel36))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtBanhKem, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel35))
                    .addComponent(cmbDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBanNhac, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaSi, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDJ, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRuou, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBanNhac, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel34))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBanhKem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaSi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMC, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDJ, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel36))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, 607));

        jLabel5.setText("Tiền Trang Trí:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 748, -1, -1));

        txtTienTrangTri.setText("30000000");
        txtTienTrangTri.setEnabled(false);
        getContentPane().add(txtTienTrangTri, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 740, 113, 30));

        jLabel6.setText("Thuế:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 748, -1, -1));

        txtThue.setText("10%");
        txtThue.setEnabled(false);
        getContentPane().add(txtThue, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 740, 40, 30));

        jLabel7.setText("Giá Thực Đơn:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 749, -1, -1));

        txtGiaThucDon.setEnabled(false);
        getContentPane().add(txtGiaThucDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 740, 124, 33));

        jLabel8.setText("Giá Dịch Vụ:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 749, -1, -1));

        txtGiaDichVu.setEnabled(false);
        getContentPane().add(txtGiaDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 740, 127, 33));

        jLabel9.setText("Số Tiền Thiếu:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 805, 80, -1));

        txtSoTienThieu.setEnabled(false);
        getContentPane().add(txtSoTienThieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 797, 124, 31));

        txtTongTien.setEnabled(false);
        getContentPane().add(txtTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 797, 127, 31));

        jLabel10.setText("Tổng Tiền:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 805, -1, -1));

        btnTinh.setText("Tính");
        btnTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhActionPerformed(evt);
            }
        });
        getContentPane().add(btnTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(831, 740, 152, 33));

        btnLapHopDong.setText("Lập Hợp Đồng");
        btnLapHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapHopDongActionPerformed(evt);
            }
        });
        getContentPane().add(btnLapHopDong, new org.netbeans.lib.awtextra.AbsoluteConstraints(831, 791, 152, 43));

        btnXemHopDong.setText("Xem Hợp Đồng");
        btnXemHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemHopDongActionPerformed(evt);
            }
        });
        getContentPane().add(btnXemHopDong, new org.netbeans.lib.awtextra.AbsoluteConstraints(861, 872, 122, 47));

        btnQuayVe.setText("Quay về Menu");
        btnQuayVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayVeActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuayVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 872, -1, 47));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("Mã Hợp Đồng Trước:");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 60, -1, -1));

        txtMaHD1.setEnabled(false);
        getContentPane().add(txtMaHD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 54, 60, 32));

        jLabel38.setIcon(new javax.swing.ImageIcon("F:\\Tai_xuong_Google\\TiecCuoi_Image\\nen.jpg")); // NOI18N
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 950));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuayVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayVeActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnQuayVeActionPerformed

    private void cmbMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMaNVActionPerformed

    private void cmbMaNVAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cmbMaNVAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMaNVAncestorRemoved

    private void cmbMaNVItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMaNVItemStateChanged
        // TODO add your handling code here:
        
         String MaNV = this.cmbMaNV.getSelectedItem().toString();
         try {
             ShowTenNV(MaNV);
            }
         catch (SQLException ex) {
             Logger.getLogger(LapHopDong.class.getName()).log(Level.SEVERE, null, ex);
         }

        
    }//GEN-LAST:event_cmbMaNVItemStateChanged

    private void cmbThucDonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbThucDonItemStateChanged
        // TODO add your handling code here:
        String MaTD = this.cmbThucDon.getSelectedItem().toString();
         try {
             ShowTD(MaTD);
            }
         catch (SQLException ex) {
             Logger.getLogger(LapHopDong.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_cmbThucDonItemStateChanged

    private void cmbDichVuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDichVuItemStateChanged
        // TODO add your handling code here:
        String MaDV = this.cmbDichVu.getSelectedItem().toString();
         try {
             ShowDV(MaDV);
            }
         catch (SQLException ex) {
             Logger.getLogger(LapHopDong.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_cmbDichVuItemStateChanged

    private void btnTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhActionPerformed
        // TODO add your handling code here:
        
        int slban = Integer.parseInt((String)cmbSoLuongBan.getSelectedItem());
        int slnv = Integer.parseInt((String)cmbSoLuongNV.getSelectedItem());
        
        //int giathucdon = Integer.parseInt(txtGiaThucDon.getText());
        double giathucdon = Double.parseDouble(txtGiaThucDon.getText());
        double tientd = slban * giathucdon;
        //int giadichvu = Integer.parseInt(txtGiaDichVu.getText());
        double giadichvu = Double.parseDouble(txtGiaDichVu.getText());
        // Thue = 10%
        double trangtri = Double.parseDouble(txtTienTrangTri.getText());
        
        double tongtien1 =  (trangtri + giadichvu +tientd + (slnv * 300000));
        double thue = tongtien1/10;  
        double tongtien = tongtien1 + thue;
        
        double tiencoc = Double.parseDouble(txtTienCoc.getText());
        double tienthieu = tongtien - tiencoc;
        
        DecimalFormat formatter = new DecimalFormat("###");
        
        if(tiencoc == 0)
            JOptionPane.showMessageDialog(null,"Vui long nhap tien coc","Thong bao",1);
        else
        {
            if(tiencoc >= 50000000)
                txtSoTienThieu.setText(formatter.format(tienthieu));
            else
                JOptionPane.showMessageDialog(null,"Tien coc phai tren 50.000.000VND","Thong bao",1);
        }
 
        txtTongTien.setText(formatter.format(tongtien));
        
        
        
    }//GEN-LAST:event_btnTinhActionPerformed

    private void btnLapHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapHopDongActionPerformed
        // TODO add your handling code here:
        
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=QLNhaHangTC;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            String sql = "insert into ThongTinKhachHang" + "(MaKhachHang,NgayLap,TenKhachHang,TenChuRe,TenCoDau,DiaChi,DienThoai,NgayToChuc,TienCoc)"
                    +("values(?,?,?,?,?,?,?,?,?)");
            
            PreparedStatement pst = con.prepareStatement(sql);
            
            
            String MaKH = txtMaHD.getText();
            java.util.Date date = txtNgayLap.getDate();
            String NgayLap = DateFormat.getDateInstance().format(date);
            String TenKH = txtTenKhachHang.getText();
            String TenChuRe = txtTenChuRe.getText();
            String TenCoDau = txtTenCoDau.getText();
            String DiaChi = txtDiaChi.getText();
            String DienThoai = txtSDT.getText();
            java.util.Date date1 = txtNgayToChuc.getDate();
            String NgayToChuc = DateFormat.getDateInstance().format(date1);
            double TienCoc = Double.parseDouble(txtTienCoc.getText());
            //------------------------------------------------------------------
           
            
            
            
            //------------------------------------------------------------------
            
            
            if(TenChuRe.length()==0||TenCoDau.length()==0 || NgayLap.length()==0||TenKH.length()==0||TenChuRe.length()==0||TenCoDau.length()==0||DiaChi.length()==0||DienThoai.length()==0||NgayToChuc.length()==0||txtSoTienThieu.getText().length()==0 ) 
                JOptionPane.showMessageDialog(null,"Vui long nhap day du ","Thong bao",1);
            else    
            {
                pst.setString(1,MaKH);
                pst.setString(2,NgayLap);
                pst.setString(3,TenKH);
                pst.setString(4,TenChuRe);
                pst.setString(5,TenCoDau);
                pst.setString(6,DiaChi);
                pst.setString(7,DienThoai);
                pst.setString(8,NgayToChuc);
                pst.setDouble(9,TienCoc);
                pst.executeUpdate();
                
                
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=QLNhaHangTC;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            String sql = "insert into ThongTinDatTiec" + "(MaDatTiec,MaDichVu,MaKhachHang,MaThucDon,MaNhanVien,SoLuongNhanVien,SoLuongBan,TongTien)"
                    +("values(?,?,?,?,?,?,?,?)");
            
            PreparedStatement pst = con.prepareStatement(sql); 
            //------------------------------------------------------------------
            String MaDT = txtMaHD.getText();
            String MaDichVu = this.cmbDichVu.getSelectedItem().toString();
            String MaKH = txtMaHD.getText();
            String MaThucDon = this.cmbThucDon.getSelectedItem().toString();
            String MaNhanVien = this.cmbMaNV.getSelectedItem().toString();
            int SoLuongBan = Integer.parseInt((String)cmbSoLuongBan.getSelectedItem());
            int SoLuongNhanVien = Integer.parseInt((String)cmbSoLuongNV.getSelectedItem());
            DecimalFormat formatter = new DecimalFormat("");
            double tongtien = Double.parseDouble(txtTongTien.getText());
            //txtTongTien.setText(formatter.format(tongtien));
            
            
            
            //------------------------------------------------------------------
            
            
            if(txtSoTienThieu.getText().length()==0 ) 
                JOptionPane.showMessageDialog(null,"Vui long nhap day du ","Thong bao",1);
            else    
            {
                pst.setString(1,MaKH);
                pst.setString(2,MaDichVu);
                pst.setString(3,MaDT);
                pst.setString(4,MaThucDon);
                pst.setString(5,MaNhanVien);
                pst.setInt(6,SoLuongNhanVien);
                pst.setInt(7,SoLuongBan);              
                pst.setDouble(8,tongtien);
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(null,"Them Thanh Cong ","Thong bao",1);
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
        
        
        
        
    }//GEN-LAST:event_btnLapHopDongActionPerformed

    private void btnXemHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemHopDongActionPerformed
         try {
             // TODO add your handling code here:
             XemHopDong xemdh = new XemHopDong();
             xemdh.setVisible(true);
             setVisible(false);
         } catch (SQLException ex) {
             Logger.getLogger(LapHopDong.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_btnXemHopDongActionPerformed

    public final void ShowDataKH()
    {
        ResultSet result = null;
        try{
            result = hd.ShowMaKH();
            while(result.next())
            {                             
                txtMaHD1.setText(String.valueOf(result.getInt(1)));
//                String a = txtMaHD.getText();
//                String b= a +1;
//                txtMaHD.setText(b);
            }
        }
        catch(SQLException e)
        {
            
        }
    }
    
    public final void ShowDataCmbNV()
    {
        ResultSet result = null;
        try{
            result = nv.ShowNhanVien();
            while(result.next())
            {
                this.cmbMaNV.addItem(result.getString("MaNhanVien"));
            }
        }
        catch(SQLException e)
        {
            
        }
    }
    
    public void ShowTenNV(String MaNV) throws SQLException
    {
            ResultSet result = nv.ShowNhanVien(MaNV);
            if(result.next())
            {
                txtTenNV.setText(result.getString("TenNhanVien"));
            }
    
    }
    
    public final void ShowDataCmbTD()
    {
        ResultSet result = null;
        try{
            result = hd.ShowThucDon();
            while(result.next())
            {
                this.cmbThucDon.addItem(result.getString("MaThucDon"));
            }
        }
        catch(SQLException e)
        {
            
        }
    }
    
    public void ShowTD(String MaTD) throws SQLException
    {
        
            ResultSet result = hd.ShowThucDon(MaTD);
            if(result.next())
            {
                txtMonKhaiVi.setText(result.getString("MonKhaiVi"));
                txtMonChinh1.setText(result.getString("MonChinh1"));
                txtMonChinh2.setText(result.getString("MonChinh2"));
                txtMonChinh3.setText(result.getString("MonChinh3"));
                txtLau.setText(result.getString("Lau"));
                txtTrangMieng.setText(result.getString("TrangMieng")); 
                txtBia.setText(result.getString("Bia"));
                txtNuocNgot.setText(result.getString("NuocNgot"));               
                txtGiaThucDon.setText(result.getString("GiaThucDon"));
                
            }
    
    }
    
    public final void ShowDataCmbDV()
    {
        ResultSet result = null;
        try{
            result = hd.ShowDichVu();
            while(result.next())
            {
                this.cmbDichVu.addItem(result.getString("MaDIchVu"));
            }
        }
        catch(SQLException e)
        {
            
        }
    }
    
    public void ShowDV(String MaDV) throws SQLException
    {
            ResultSet result = hd.ShowDichVu(MaDV);
            if(result.next())
            {
                txtRuou.setText(result.getString("Ruou"));
                txtBanhKem.setText(result.getString("BanhKem"));
                txtMC.setText(result.getString("MC"));
                txtBanNhac.setText(result.getString("BanNhac"));
                txtCaSi.setText(result.getString("CaSi"));
                txtDJ.setText(result.getString("DJ"));
                txtGiaDichVu.setText(result.getString("GiaDichVu"));

               
                
            }
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LapHopDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LapHopDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LapHopDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LapHopDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LapHopDong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLapHopDong;
    private javax.swing.JButton btnQuayVe;
    private javax.swing.JButton btnTinh;
    private javax.swing.JButton btnXemHopDong;
    private javax.swing.JComboBox cmbDichVu;
    private javax.swing.JComboBox cmbMaNV;
    private javax.swing.JComboBox cmbSoLuongBan;
    private javax.swing.JComboBox cmbSoLuongNV;
    private javax.swing.JComboBox cmbThucDon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField txtBanNhac;
    private javax.swing.JTextField txtBanhKem;
    private javax.swing.JTextField txtBia;
    private javax.swing.JTextField txtCaSi;
    private javax.swing.JTextField txtDJ;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtGiaDichVu;
    private javax.swing.JTextField txtGiaThucDon;
    private javax.swing.JTextField txtLau;
    private javax.swing.JTextField txtMC;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMaHD1;
    private javax.swing.JTextField txtMonChinh1;
    private javax.swing.JTextField txtMonChinh2;
    private javax.swing.JTextField txtMonChinh3;
    private javax.swing.JTextField txtMonKhaiVi;
    private com.toedter.calendar.JDateChooser txtNgayLap;
    private com.toedter.calendar.JDateChooser txtNgayToChuc;
    private javax.swing.JTextField txtNuocNgot;
    private javax.swing.JTextField txtRuou;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSoTienThieu;
    private javax.swing.JTextField txtTenChuRe;
    private javax.swing.JTextField txtTenCoDau;
    private javax.swing.JTextField txtTenKhachHang;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtThue;
    private javax.swing.JTextField txtTienCoc;
    private javax.swing.JTextField txtTienTrangTri;
    private javax.swing.JTextField txtTongTien;
    private javax.swing.JTextField txtTrangMieng;
    // End of variables declaration//GEN-END:variables
}
