/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlnhahangtieccuoi;

import Process.HopDong;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thang Le
 */
public class XemHopDong extends javax.swing.JFrame {

    private final DefaultTableModel tableModel = new DefaultTableModel();
    private final DefaultTableModel tableMode2 = new DefaultTableModel();
    HopDong hd = new HopDong();
    /**
     * Creates new form XemHopDong
     */
    public XemHopDong()throws SQLException {
        initComponents();
        ImageIcon img = new ImageIcon("E:\\java\\QLNhaHang\\QLNhaHangTiecCuoi\\src\\Database/2.jpg");
        this.setIconImage(img.getImage());
        String []colsName = {"Mã Khách Hàng","Ngày Lập","Tên Khách Hàng","Tên Chú Rể","Tên Cô Dâu", "Địa Chỉ","SDT", "Ngày Tổ Chức","Tiền Cọc"};
        String []colsName1 = {"Mã Đặt Tiệc","Mã Dịch Vụ","Mã Khách Hàng","Mã Thực Đơn","Mã Nhân Viên", "Số Luongj Nhân Viên","Số Lượng Bàn","Tổng Tiền"};
        
     // đặt tiêu đề cột cho tableModel
        tableModel.setColumnIdentifiers(colsName); 
        tableMode2.setColumnIdentifiers(colsName1); 
        // kết nối jtable với tableModel 
        tabDsHD.setModel(tableModel);
        tabDsHD1.setModel(tableMode2); 
        //gọi hàm ShowData để đưa dữ liệu vào tableModel 
        ShowDs(); 
        ShowDsDT();
    }

    public void ShowDs() throws SQLException{ 
         
 
    try { 
        ResultSet result= hd.ShowTTKH();
        //ResultSet resultDT= hd.ShowTTDT();
        while(result.next())
        { // nếu còn đọc tiếp được một dòng dữ liệu
            String rows[] = new String[9];
             // lấy dữ liệu tại cột số 1 (ứng với mã kh)
            rows[0] = result.getString(1);
            rows[1] = result.getString(2); 
            rows[2] = result.getString(3);
            rows[3] = result.getString(4);
            rows[4] = result.getString(5);
            rows[5] = result.getString(6);
            rows[6] = result.getString(7);            
            rows[7] = result.getString(8);
            rows[8] = result.getString(9);

            tableModel.addRow(rows); // đưa dòng dữ liệu vào tableModel 
            //mỗi lần có sự thay đổi dữ liệu ở tableModel thì Jtable sẽ tự động update 
        }
        
    } 
    catch (SQLException e) {
        JOptionPane.showMessageDialog(null,e);
    } 
    } 
    
    public void ShowDsDT() throws SQLException{ 
         
 
    try { 
        ResultSet result= hd.ShowTTDT();
        //ResultSet resultDT= hd.ShowTTDT();
        while(result.next())
        { // nếu còn đọc tiếp được một dòng dữ liệu
            String rows[] = new String[8];
             // lấy dữ liệu tại cột số 1 (ứng với mã dt)
            rows[0] = result.getString(1);
            rows[1] = result.getString(2); 
            rows[2] = result.getString(3);
            rows[3] = result.getString(4);
            rows[4] = result.getString(5);
            rows[5] = result.getString(6);
            rows[6] = result.getString(7);            
            rows[7] = result.getString(8);
            
            tableMode2.addRow(rows); // đưa dòng dữ liệu vào tableModel 
            //mỗi lần có sự thay đổi dữ liệu ở tableModel thì Jtable sẽ tự động update 
        }
        
    } 
    catch (SQLException e) {
        JOptionPane.showMessageDialog(null,e);
    } 
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabDsHD = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabDsHD1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnXoaTTKH = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách hợp đồng"));

        tabDsHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabDsHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabDsHDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabDsHD);

        tabDsHD1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabDsHD1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabDsHD1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabDsHD1);

        jLabel2.setText("Thông tin đặt tiệc");

        jLabel3.setText("Thông tin khách hàng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(380, 380, 380))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 114, -1, -1));
        jPanel1.getAccessibleContext().setAccessibleParent(jPanel1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DANH SÁCH HỢP ĐỒNG");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 11, -1, -1));

        btnXoaTTKH.setText("Xóa Thông Tin Khách");
        btnXoaTTKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTTKHActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoaTTKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 655, -1, -1));

        jButton2.setText("Quay lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 655, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Mã:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 63, -1, -1));

        txtMa.setEditable(false);
        txtMa.setEnabled(false);
        getContentPane().add(txtMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 55, 31, 31));

        jLabel5.setIcon(new javax.swing.ImageIcon("F:\\Tai_xuong_Google\\TiecCuoi_Image\\nen.jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        LapHopDong laphd = new LapHopDong();
        laphd.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void ClearData() throws SQLException{
    //Lay chi so dong cuoi cung
    int n=tableModel.getRowCount()-1;
    for(int i=n;i>=0;i--)
    tableModel.removeRow(i);//Remove tung dong 
    }
    public void ClearData1() throws SQLException{
    //Lay chi so dong cuoi cung
    int n=tableMode2.getRowCount()-1;
    for(int i=n;i>=0;i--)
    tableMode2.removeRow(i);//Remove tung dong 
    }
    private void btnXoaTTKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTTKHActionPerformed
        // TODO add your handling code here:
    String Ma =txtMa.getText();
    try 
    {
        if(Ma.length()==0) 
            JOptionPane.showMessageDialog(null,"Chọn 1 mã để xóa","Thông Báo",1);
        else
        {
            if(JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa Mã  " + Ma,"Thông Báo",2)==0)
                { 
                    hd.DeleteDT(Ma);//goi ham xoa du lieu theo ma loai
                    hd.DeleteHD(Ma);
                    ClearData();//Xoa du lieu trong tableModel
                    ClearData1();
                    ShowDs();//Do du lieu vao table Model
                    ShowDsDT();
                    JOptionPane.showMessageDialog(null,"Xóa Thành Công!","Thong bao",1);
                //setNull();//Xoa trang Textfield
                }
        }
    } 
    catch (SQLException ex) 
    {
        JOptionPane.showMessageDialog(null,"Xóa thất bại!","Thong bao",1);
    }
        
    }//GEN-LAST:event_btnXoaTTKHActionPerformed

    private void tabDsHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabDsHDMouseClicked
        // TODO add your handling code here:
        try{
            //Lay chi so dong dang chon
            int row =this.tabDsHD.getSelectedRow();
            String ml=(this.tabDsHD.getModel().getValueAt(row,0)).toString();
            ResultSet rs= hd.ShowHopDongKH(ml);//Goi ham lay du lieu theo ma
            if(rs.next())//Neu co du lieu
            {
                this.txtMa.setText(rs.getString("MaKhachHang"));
            }
        }
        catch (SQLException e) {
        }
    }//GEN-LAST:event_tabDsHDMouseClicked

    private void tabDsHD1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabDsHD1MouseClicked
        // TODO add your handling code here:
        try{
            //Lay chi so dong dang chon
            int row =this.tabDsHD1.getSelectedRow();
            String ml=(this.tabDsHD1.getModel().getValueAt(row,0)).toString();
            ResultSet rs= hd.ShowHopDong(ml);//Goi ham lay du lieu theo ma
            if(rs.next())//Neu co du lieu
            {
                this.txtMa.setText(rs.getString("MaDatTiec"));
            }
        }
        catch (SQLException e) {
        }
    }//GEN-LAST:event_tabDsHD1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XemHopDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XemHopDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XemHopDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XemHopDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new XemHopDong().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(XemHopDong.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXoaTTKH;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabDsHD;
    private javax.swing.JTable tabDsHD1;
    private javax.swing.JTextField txtMa;
    // End of variables declaration//GEN-END:variables
}
